import axios from "axios";
import {url} from "./apiData"

export async function getSubjects(){
  try {
    const response = await axios.get(`${url}/options?option=subject`)
    return response.data.body.options

  } catch (error) {
      console.error('An error occurred:', error);
      throw new Error(`An unexpected error occurred. Please try again later.`);
    }
  }
  

  export async function createSubject(subjectData) {
    try {
     await axios.post(`${url}/options?option=subject`,subjectData)
    } catch (error) {
      console.error('An error occurred:', error);
      throw new Error(`An unexpected error occurred. Please try again later.`);
    }
  }

  export async function deleteSubject(subjectId) {
    try {
     await axios.delete(`${url}/options/${subjectId}?option=subject`)

    } catch (error) {
      console.error('An error occurred:', error);
      throw new Error(`An unexpected error occurred. Please try again later.`);
    }
  }







  export async function getHalls(){
    try {
      const response = await axios.get(`${url}/options?option=hall`)
      console.log(response.data);
      return response.data.body.options
      
  
    } catch (error) {
        console.error('An error occurred:', error);
        throw new Error(`An unexpected error occurred. Please try again later.`);
      }
    }
    
  
    export async function createHall(hallData) {
      try {
       await axios.post(`${url}/options?option=hall`,hallData)
      } catch (error) {
        console.error('An error occurred:', error);
        throw new Error(`An unexpected error occurred. Please try again later.`);
      }
    }
  
    export async function deleteHall(hallId) {
      try {
       await axios.delete(`${url}/options/${hallId}?option=hall`)
  
      } catch (error) {
        console.error('An error occurred:', error);
        throw new Error(`An unexpected error occurred. Please try again later.`);
      }
    }



    export async function getGrades(){
        try {
          const response = await axios.get(`${url}/options?option=grade`)
          return response.data.body.options
      
        } catch (error) {
            console.error('An error occurred:', error);
            throw new Error(`An unexpected error occurred. Please try again later.`);
          }
        }
        
      
        export async function createGrade(gradeData) {
          try {
           await axios.post(`${url}/options?option=grade`,gradeData)
          } catch (error) {
            console.error('An error occurred:', error);
            throw new Error(`An unexpected error occurred. Please try again later.`);
          }
        }
      
        export async function deleteGrade(gradeId) {
          try {
           await axios.delete(`${url}/options/${gradeId}?option=grade`)
      
          } catch (error) {
            console.error('An error occurred:', error);
            throw new Error(`An unexpected error occurred. Please try again later.`);
          }
        }